export const CITIES_MX = [
  { production: 'Acapulco, Guerrero',             homologation: 'Acapulco, GR',         stateCode: 'GR' },
  { production: 'Aguascalientes, Aguascalientes',  homologation: 'Aguascalientes, AG',    stateCode: 'AG' },
  { production: 'Altamira, Tamaulipas',            homologation: 'Altamira, TM',          stateCode: 'TM' },
  { production: 'Campeche, Campeche',              homologation: 'Campeche, CM',          stateCode: 'CM' },
  { production: 'Cancun, Quintana Roo',            homologation: 'Cancun, QR',            stateCode: 'QR' },
  { production: 'Cd. Acuña, Coahuila',             homologation: 'Cd. Acuña, CU',         stateCode: 'CU' },
  { production: 'Cd. Hidalgo, Chiapas',            homologation: 'Cd. Hidalgo, CS',       stateCode: 'CS' },
  { production: 'Cd. Juarez, Chihuahua',           homologation: 'Cd. Juarez, CH',        stateCode: 'CH' },
  { production: 'Cd. Obregon, Sonora',             homologation: 'Cd. Obregon, SO',       stateCode: 'SO' },
  { production: 'Cd. Victoria, Tamaulipas',        homologation: 'Cd. Victoria, TM',      stateCode: 'TM' },
  { production: 'Chihuahua, Chihuahua',            homologation: 'Chihuahua, CH',         stateCode: 'CH' },
  { production: 'Coatzacoalcos, Veracruz',         homologation: 'Coatzacoalcos, VE',     stateCode: 'VE' },
  { production: 'Cuernavaca, Morelos',             homologation: 'Cuernavaca, MR',        stateCode: 'MR' },
  { production: 'Culiacan, Sinaloa',               homologation: 'Culiacan, SI',          stateCode: 'SI' },
  { production: 'Durango, Durango',                homologation: 'Durango, DU',           stateCode: 'DU' },
  { production: 'Ensenada, Baja California',       homologation: 'Ensenada, BN',          stateCode: 'BN' },
  { production: 'Guadalajara, Jalisco',            homologation: 'Guadalajara, JA',       stateCode: 'JA' },
  { production: 'Guanajuato, Guanajuato',          homologation: 'Guanajuato, GJ',        stateCode: 'GJ' },
  { production: 'Hermosillo, Sonora',              homologation: 'Hermosillo, SO',        stateCode: 'SO' },
  { production: 'Irapuato, Guanajuato',            homologation: 'Irapuato, GJ',          stateCode: 'GJ' },
  { production: 'La Paz, Baja California Sur',     homologation: 'La Paz, BS',            stateCode: 'BS' },
  { production: 'Lazaro Cardenas, Michoacan',      homologation: 'Lazaro Cardenas, MC',   stateCode: 'MC' },
  { production: 'Leon, Guanajuato',                homologation: 'Leon, GJ',              stateCode: 'GJ' },
  { production: 'Los Mochis, Sinaloa',             homologation: 'Los Mochis, SI',        stateCode: 'SI' },
  { production: 'Manzanillo, Colima',              homologation: 'Manzanillo, CL',        stateCode: 'CL' },
  { production: 'Martinez de la Torre, Veracruz',  homologation: 'Martinez de la Torre, VE', stateCode: 'VE' },
  { production: 'Matamoros, Tamaulipas',           homologation: 'Matamoros, TM',         stateCode: 'TM' },
  { production: 'Mazatlan, Sinaloa',               homologation: 'Mazatlan, SI',          stateCode: 'SI' },
  { production: 'Merida, Yucatan',                 homologation: 'Merida, YU',            stateCode: 'YU' },
  { production: 'Mexicali, Baja California',       homologation: 'Mexicali, BN',          stateCode: 'BN' },
  { production: 'Mexico, DF',                      homologation: 'Mexico, DF',            stateCode: 'DF' },
  { production: 'Monclova, Coahuila',              homologation: 'Monclova, CU',          stateCode: 'CU' },
  { production: 'Monterrey, Nuevo Leon',           homologation: 'Monterrey, NL',         stateCode: 'NL' },
  { production: 'Morelia, Michoacan',              homologation: 'Morelia, MC',           stateCode: 'MC' },
  { production: 'Nogales, Sonora',                 homologation: 'Nogales, SO',           stateCode: 'SO' },
  { production: 'Nuevo Laredo, Tamaulipas',        homologation: 'Nuevo Laredo, TM',      stateCode: 'TM' },
  { production: 'Oaxaca, Oaxaca',                  homologation: 'Oaxaca, OA',            stateCode: 'OA' },
  { production: 'Pachuca, Hidalgo',                homologation: 'Pachuca, HG',           stateCode: 'HG' },
  { production: 'Piedras Negras, Coahuila',        homologation: 'Piedras Negras, CU',    stateCode: 'CU' },
  { production: 'Puebla, Puebla',                  homologation: 'Puebla, PB',            stateCode: 'PB' },
  { production: 'Puerto Vallarta, Jalisco',        homologation: 'Puerto Vallarta, JA',   stateCode: 'JA' },
  { production: 'Queretaro, Queretaro',            homologation: 'Queretaro, QE',         stateCode: 'QE' },
  { production: 'Ramos Arizpe, Coahuila',          homologation: 'Ramos Arizpe, CU',      stateCode: 'CU' },
  { production: 'Reynosa, Tamaulipas',             homologation: 'Reynosa, TM',           stateCode: 'TM' },
  { production: 'Saltillo, Coahuila',              homologation: 'Saltillo, CU',          stateCode: 'CU' },
  { production: 'San Luis Potosi, San Luis Potosi', homologation: 'San Luis Potosi, SL',  stateCode: 'SL' },
  { production: 'Tampico, Tamaulipas',             homologation: 'Tampico, TM',           stateCode: 'TM' },
  { production: 'Tapachula, Chiapas',              homologation: 'Tapachula, CS',         stateCode: 'CS' },
  { production: 'Tehuacan, Puebla',                homologation: 'Tehuacan, PB',          stateCode: 'PB' },
  { production: 'Tepeji del Rio, Hidalgo',         homologation: 'Tepeji del Rio, HG',    stateCode: 'HG' },
  { production: 'Tepic, Nayarit',                  homologation: 'Tepic, NA',             stateCode: 'NA' },
  { production: 'Tijuana, Baja California',        homologation: 'Tijuana, BN',           stateCode: 'BN' },
  { production: 'Tlaxcala, Tlaxcala',              homologation: 'Tlaxcala, TL',          stateCode: 'TL' },
  { production: 'Toluca, Mexico',                  homologation: 'Toluca, MX',            stateCode: 'MX' },
  { production: 'Torreon, Coahuila',               homologation: 'Torreon, CU',           stateCode: 'CU' },
  { production: 'Tuxtla Gutierrez, Chiapas',       homologation: 'Tuxtla Gutierrez, CS',  stateCode: 'CS' },
  { production: 'Veracruz, Veracruz',              homologation: 'Veracruz, VE',          stateCode: 'VE' },
  { production: 'Villahermosa, Tabasco',           homologation: 'Villahermosa, TB',      stateCode: 'TB' },
  { production: 'Xalapa, Veracruz',               homologation: 'Xalapa, VE',            stateCode: 'VE' },
  { production: 'Zacatecas, Zacatecas',            homologation: 'Zacatecas, ZA',         stateCode: 'ZA' },
]
